#!/usr/bin/env bash
# ClaimTrace — installer
# Multi-platform: pi / Cursor / Copilot / oh-my-pi (omp)
# 借鉴 llm-wiki-okf 设计：脚本安装到 ~/.local/bin/

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

success() { echo -e "${GREEN}✓${NC} $1"; }
warn()    { echo -e "${YELLOW}!${NC} $1"; }
fail()    { echo -e "${RED}✗${NC} $1"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$SCRIPT_DIR"
BIN_DIR="${WIKI_BIN_DIR:-${HOME}/.local/bin}"

# === 1. Detect agent platform ===
detect_platform() {
  if [ -d "${SCRIPT_DIR}/.pi" ] || [ -d "${HOME}/.pi" ]; then
    echo "pi"
  elif [ -d "${SCRIPT_DIR}/.omp" ] || [ -d "${HOME}/.omp" ]; then
    echo "oh-my-pi"
  elif [ -d "${SCRIPT_DIR}/.claude" ]; then
    echo "claude-code"
  else
    echo ""
  fi
}

PLATFORM="$(detect_platform || true)"
[ -n "${PLATFORM}" ] && success "Detected platform: ${PLATFORM}" || warn "No agent config detected — Skill 可手动 link"

# === 2. Install unified `wiki` CLI to BIN_DIR ===
install_cli() {
  mkdir -p "${BIN_DIR}"

  cat > "${BIN_DIR}/wiki" <<EOF
#!/usr/bin/env bash
# ClaimTrace unified CLI
# Generated by install.sh at $(date -Iseconds)
exec python3 "${SKILL_DIR}/scripts/wiki_common.py" "\$@"
EOF
  chmod +x "${BIN_DIR}/wiki"

  success "Installed wiki CLI → ${BIN_DIR}/wiki"

  # Verify PATH
  if [[ ":${PATH}:" != *":${BIN_DIR}:"* ]]; then
    warn "${BIN_DIR} not in PATH. Add to ~/.bashrc: export PATH=\${HOME}/.local/bin:\${PATH}"
  fi
}

# === 3. Symlink skill into agent config ===
install_skill_link() {
  case "${PLATFORM}" in
    pi|oh-my-pi)
      local AGENT_DIR="${SCRIPT_DIR}/.${PLATFORM%"-"*}"  # .pi or .omp
      mkdir -p "${AGENT_DIR}/skills"
      ln -sf "${SKILL_DIR}" "${AGENT_DIR}/skills/claimtrace"
      success "Linked skill → ${AGENT_DIR}/skills/claimtrace"
      ;;
    claude-code)
      mkdir -p "${SCRIPT_DIR}/.claude/skills"
      ln -sf "${SKILL_DIR}" "${SCRIPT_DIR}/.claude/skills/claimtrace"
      success "Linked skill → .claude/skills/claimtrace"
      ;;
    "")
      warn "No platform detected — Skill link skipped. Manually link:"
      echo "    ln -s ${SKILL_DIR} ~/.pi/skills/claimtrace"
      ;;
  esac
}

# === 4. Verify Python version ===
check_python() {
  if ! command -v python3 &> /dev/null; then
    fail "python3 not found. Install Python 3.8+ first."
  fi

  local PY_MAJOR PY_MINOR
  PY_MAJOR="$(python3 -c 'import sys; print(sys.version_info.major)')"
  PY_MINOR="$(python3 -c 'import sys; print(sys.version_info.minor)')"

  if [ "${PY_MAJOR}" -lt 3 ] || { [ "${PY_MAJOR}" -eq 3 ] && [ "${PY_MINOR}" -lt 8 ]; }; then
    fail "Python ${PY_MAJOR}.${PY_MINOR} found, need 3.8+"
  fi

  success "Python ${PY_MAJOR}.${PY_MINOR} OK"
}

# === 5. Run install ===
main() {
  echo "=========================================="
  echo "ClaimTrace Installer"
  echo "=========================================="
  echo ""

  check_python
  install_cli
  install_skill_link

  echo ""
  echo "=========================================="
  echo "✓ Installation complete"
  echo "=========================================="
  echo ""
  echo "Next steps:"
  echo "  1. cd <your-research-project>"
  echo "  2. wiki init                          # initialize wiki structure"
  echo "  3. Place paper PDFs in zotero_mn/..."
  echo "  4. Run MinerU to get full.md"
  echo "  5. In pi: '处理 /path/to/paper.pdf'"
  echo ""
  echo "Documentation: ${SKILL_DIR}/references/AGENTS.md"
}

main "$@"